# https://prettier.io/docs/en/options.html
# https://prettier.io/docs/en/configuration.html

# Use single quotes instead of double quotes.
# https://prettier.io/docs/en/options.html#quotes
singleQuote: false
